version: "3.8"
services:
  redis:
    image: redis:6-alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - blueprint
  postgres:
    image: postgres:16-alpine
    restart: always
    container_name: postgres
    networks:
      - blueprint
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: platform_core
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: root@12345
      TZ: 'UTC'
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
networks:
  blueprint:
    name: blueprint
    driver: bridge