// By Emran A. Hamdan, Lead Architect
// Comment of why this proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/blueprint/blueprint.proto

package blueprint

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Blueprint_Call_FullMethodName = "/blueprint.Blueprint/Call"
)

// BlueprintClient is the client API for Blueprint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlueprintClient interface {
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
}

type blueprintClient struct {
	cc grpc.ClientConnInterface
}

func NewBlueprintClient(cc grpc.ClientConnInterface) BlueprintClient {
	return &blueprintClient{cc}
}

func (c *blueprintClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, Blueprint_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlueprintServer is the server API for Blueprint service.
// All implementations must embed UnimplementedBlueprintServer
// for forward compatibility.
type BlueprintServer interface {
	Call(context.Context, *CallRequest) (*CallResponse, error)
	mustEmbedUnimplementedBlueprintServer()
}

// UnimplementedBlueprintServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlueprintServer struct{}

func (UnimplementedBlueprintServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedBlueprintServer) mustEmbedUnimplementedBlueprintServer() {}
func (UnimplementedBlueprintServer) testEmbeddedByValue()                   {}

// UnsafeBlueprintServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlueprintServer will
// result in compilation errors.
type UnsafeBlueprintServer interface {
	mustEmbedUnimplementedBlueprintServer()
}

func RegisterBlueprintServer(s grpc.ServiceRegistrar, srv BlueprintServer) {
	// If the following call pancis, it indicates UnimplementedBlueprintServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Blueprint_ServiceDesc, srv)
}

func _Blueprint_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlueprintServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blueprint_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlueprintServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Blueprint_ServiceDesc is the grpc.ServiceDesc for Blueprint service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Blueprint_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blueprint.Blueprint",
	HandlerType: (*BlueprintServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Blueprint_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/blueprint/blueprint.proto",
}
