// By Emran A. Hamdan, Lead Architect
// Comment of why this proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/blueprint/blueprint.proto

package blueprint

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_proto_blueprint_blueprint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blueprint_blueprint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_proto_blueprint_blueprint_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_proto_blueprint_blueprint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blueprint_blueprint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_proto_blueprint_blueprint_proto_rawDescGZIP(), []int{1}
}

func (x *CallResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_blueprint_blueprint_proto protoreflect.FileDescriptor

const file_proto_blueprint_blueprint_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/blueprint/blueprint.proto\x12\tblueprint\"!\n" +
	"\vCallRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\" \n" +
	"\fCallResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2F\n" +
	"\tBlueprint\x129\n" +
	"\x04Call\x12\x16.blueprint.CallRequest\x1a\x17.blueprint.CallResponse\"\x00B\fZ\n" +
	"/blueprintb\x06proto3"

var (
	file_proto_blueprint_blueprint_proto_rawDescOnce sync.Once
	file_proto_blueprint_blueprint_proto_rawDescData []byte
)

func file_proto_blueprint_blueprint_proto_rawDescGZIP() []byte {
	file_proto_blueprint_blueprint_proto_rawDescOnce.Do(func() {
		file_proto_blueprint_blueprint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_blueprint_blueprint_proto_rawDesc), len(file_proto_blueprint_blueprint_proto_rawDesc)))
	})
	return file_proto_blueprint_blueprint_proto_rawDescData
}

var file_proto_blueprint_blueprint_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_blueprint_blueprint_proto_goTypes = []any{
	(*CallRequest)(nil),  // 0: blueprint.CallRequest
	(*CallResponse)(nil), // 1: blueprint.CallResponse
}
var file_proto_blueprint_blueprint_proto_depIdxs = []int32{
	0, // 0: blueprint.Blueprint.Call:input_type -> blueprint.CallRequest
	1, // 1: blueprint.Blueprint.Call:output_type -> blueprint.CallResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_blueprint_blueprint_proto_init() }
func file_proto_blueprint_blueprint_proto_init() {
	if File_proto_blueprint_blueprint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_blueprint_blueprint_proto_rawDesc), len(file_proto_blueprint_blueprint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_blueprint_blueprint_proto_goTypes,
		DependencyIndexes: file_proto_blueprint_blueprint_proto_depIdxs,
		MessageInfos:      file_proto_blueprint_blueprint_proto_msgTypes,
	}.Build()
	File_proto_blueprint_blueprint_proto = out.File
	file_proto_blueprint_blueprint_proto_goTypes = nil
	file_proto_blueprint_blueprint_proto_depIdxs = nil
}
