// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/blueprint/blueprint.proto

package blueprint

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlueprintClient is the client API for Blueprint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlueprintClient interface {
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
}

type blueprintClient struct {
	cc grpc.ClientConnInterface
}

func NewBlueprintClient(cc grpc.ClientConnInterface) BlueprintClient {
	return &blueprintClient{cc}
}

func (c *blueprintClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, "/blueprint.Blueprint/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlueprintServer is the server API for Blueprint service.
// All implementations must embed UnimplementedBlueprintServer
// for forward compatibility
type BlueprintServer interface {
	Call(context.Context, *CallRequest) (*CallResponse, error)
	mustEmbedUnimplementedBlueprintServer()
}

// UnimplementedBlueprintServer must be embedded to have forward compatible implementations.
type UnimplementedBlueprintServer struct {
}

func (UnimplementedBlueprintServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedBlueprintServer) mustEmbedUnimplementedBlueprintServer() {}

// UnsafeBlueprintServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlueprintServer will
// result in compilation errors.
type UnsafeBlueprintServer interface {
	mustEmbedUnimplementedBlueprintServer()
}

func RegisterBlueprintServer(s grpc.ServiceRegistrar, srv BlueprintServer) {
	s.RegisterService(&Blueprint_ServiceDesc, srv)
}

func _Blueprint_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlueprintServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blueprint.Blueprint/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlueprintServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Blueprint_ServiceDesc is the grpc.ServiceDesc for Blueprint service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Blueprint_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blueprint.Blueprint",
	HandlerType: (*BlueprintServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Blueprint_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/blueprint/blueprint.proto",
}
